name: CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        
      - name: Compile typescript
        run: npx typescript --build
        
      - name: Move files to root
        run: |
          mkdir /tmp/staging
          mv * /tmp/staging
          mv /tmp/staging/app/* .
          ls .
        
      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Deplot to gh-pages" -a
          
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          force: true
          branch: gh-pages
